#we give label to filter or select that pod for service or to run, explecit to work
kind: Pod
apiVersion: v1
metadata:
  name: labels
  labels:
    course: k8
    trainer: k8
spec:
  containers:
  - name: nginx
    image: nginx