apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat
data:   # we mount filebeat configuartion for nginx
  filebeat.yml: |
    filebeat:
      config:
        modules:
          path: /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true
      modules:
      - module: nginx
        access:
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch:
        hosts: ["elasticsearch:9200"]
---  # we configure side car
kind: Pod
apiVersion: v1
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:  # ngix volumes mounting
    - name: nginx-logs
      mountPath: /var/log/nginx/
  - name: filebeat  # side car 
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumeMounts:  # first volumes then mount it
    - name: filebeat-config
      mountPath: /usr/share/filebeat/filebeat.yml
      subPath: filebeat.yml
    - name: nginx-logs   # to access nginx logs
      mountPath: /var/log/nginx/
  volumes:  # volumes 
  - name: nginx-logs
    emptyDir: {}   # by default k8 considers volumes as emptyDir.
  - name: filebeat-config
    configMap:
      name: filebeat
      items:
        - key: filebeat.yml
          path: filebeat.yml