kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: efs-dynamic
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0c2d31a2e370dd820   # replace wil your file system id
  directoryPerms: "700"
  basePath: "/expense"  #for expense project